[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022790E6CC00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f20ed496e8c828dfc25d9d09eb663563
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022790E6CE20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f20ed496e8c828dfc25d9d09eb663563
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022790E6D150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f20ed496e8c828dfc25d9d09eb663563