[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022790E6F020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5eb7bcef914f646efa553c0fc0b39516
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022790E6F790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5eb7bcef914f646efa553c0fc0b39516
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022790E6FAC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5eb7bcef914f646efa553c0fc0b39516